Resources:
  myLovelyBucketD9F8C1F9:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: CdkIamStack/myLovelyBucket/Resource
  myAwesomeFunctionServiceRoleC4A88716:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: CdkIamStack/myAwesomeFunction/ServiceRole/Resource
  myAwesomeFunctionServiceRoleDefaultPolicyD47C46A9:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Resource:
              Fn::GetAtt:
                - myLovelyBucketD9F8C1F9
                - Arn
        Version: "2012-10-17"
      PolicyName: myAwesomeFunctionServiceRoleDefaultPolicyD47C46A9
      Roles:
        - Ref: myAwesomeFunctionServiceRoleC4A88716
    Metadata:
      aws:cdk:path: CdkIamStack/myAwesomeFunction/ServiceRole/DefaultPolicy/Resource
  myAwesomeFunction1175605B:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: AssetParametersa1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331adS3Bucket0A7EF398
        S3Key:
          Fn::Join:
            - ""
            - - Fn::Select:
                  - 0
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331adS3VersionKey18F06273
              - Fn::Select:
                  - 1
                  - Fn::Split:
                      - "||"
                      - Ref: AssetParametersa1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331adS3VersionKey18F06273
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - myAwesomeFunctionServiceRoleC4A88716
          - Arn
      Runtime: nodejs12.x
    DependsOn:
      - myAwesomeFunctionServiceRoleDefaultPolicyD47C46A9
      - myAwesomeFunctionServiceRoleC4A88716
    Metadata:
      aws:cdk:path: CdkIamStack/myAwesomeFunction/Resource
      aws:asset:path: asset.a1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331ad
      aws:asset:property: Code
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.36.1,@aws-cdk/assets=1.36.1,@aws-cdk/aws-cloudwatch=1.36.1,@aws-cdk/aws-ec2=1.36.1,@aws-cdk/aws-events=1.36.1,@aws-cdk/aws-iam=1.36.1,@aws-cdk/aws-kms=1.36.1,@aws-cdk/aws-lambda=1.36.1,@aws-cdk/aws-logs=1.36.1,@aws-cdk/aws-s3=1.36.1,@aws-cdk/aws-s3-assets=1.36.1,@aws-cdk/aws-sqs=1.36.1,@aws-cdk/aws-ssm=1.36.1,@aws-cdk/cloud-assembly-schema=1.36.1,@aws-cdk/core=1.36.1,@aws-cdk/cx-api=1.36.1,@aws-cdk/region-info=1.36.1,jsii-runtime=node.js/v13.13.0
    Condition: CDKMetadataAvailable
Parameters:
  AssetParametersa1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331adS3Bucket0A7EF398:
    Type: String
    Description: S3 bucket for asset "a1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331ad"
  AssetParametersa1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331adS3VersionKey18F06273:
    Type: String
    Description: S3 key for asset version "a1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331ad"
  AssetParametersa1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331adArtifactHash00D2AAF1:
    Type: String
    Description: Artifact hash for asset "a1a8fc554de8fb4fdd4a412bf1f0593fc354b9cabd398fb1e74c03e7d49331ad"
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

